# Generated by Django 4.1.1 on 2022-09-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.ForeignKey(default=99999999999, on_delete=django.db.models.deletion.CASCADE, to='cliente.cpf'),
            preserve_default=False,
        ),
    ]
