# Generated by Django 4.1.1 on 2022-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
    ]
