# Generated by Django 4.1.1 on 2022-09-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.ManyToManyField(to='cliente.cidade'),
        ),
    ]
